name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Set up AWS credentials
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        mkdir -p ~/.aws
        touch ~/.aws/credentials
        echo "[default]
        aws_access_key_id = $AWS_ACCESS_KEY_ID
        aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials

    - name: Upload to S3
      run: | 
        aws s3 cp ./dags/cleanup.py s3://${{secrets.S3_BUCKET}}/dags/cleanup.py --region eu-central-1
        aws s3 cp ./dags/crawler.py s3://${{secrets.S3_BUCKET}}/dags/crawler.py --region eu-central-1
        aws s3 cp ./dags/glue_job.py s3://${{secrets.S3_BUCKET}}/dags/glue_job.py --region eu-central-1
        aws s3 cp ./dags/main_orchestrator.py s3://${{secrets.S3_BUCKET}}/dags/main_orchestrator.py --region eu-central-1

    - name: Cleanup credentials
      run: rm -rf ~/.aws

    - name: Build
      run: ./mwaa-local-env build-image
